name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install -g yarn && yarn install
      - name: Build🔧
        run: yarn run clean && yarn run build
      - name: Configuration environment🙌
        env:
          HEXO_DEPLOY_PRI: ${{secrets.DEPLOY_HEXO}}
        run: |
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "TsungKang"
          git config --global user.email "tsungkang@live.cn"
      - name: Deploy🚀
        run: |
          npm run deploy && rm -f ~/.ssh/id_rsa
